# Generated by Django 4.1.2 on 2023-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('cpassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
